In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
#загрузка данных
benchmark_queries = pd.read_parquet('/kaggle/input/datasets/khamitovdanil/data-for-avito/benchmark_queries.parquet')

benchmark_items = pd.read_parquet('/kaggle/input/datasets/khamitovdanil/data-for-avito/benchmark_items.parquet')

train = pd.read_parquet('/kaggle/input/datasets/khamitovdanil/data-for-avito/train.parquet')

print(f"Размер тестовых запросов: {benchmark_queries.shape}")
print(f"Размер базы объявлений: {benchmark_items.shape}")
print(f"Размер трейна: {train.shape}")

Размер тестовых запросов: (2452, 6)
Размер базы объявлений: (189212, 14)
Размер трейна: (497673, 19)

In [3]:
#посмотреть как выглядят данные
display(train.head(5))
display(benchmark_items.head(5))
display(benchmark_queries.head(5))

,search_query,search_location_id,search_is_delivery_search,search_infm_params_text,search_category,item_title_raw,item_rating_reviews_count,item_rating,item_price,item_microcat_id,item_longitude,item_location_id,item_latitude,item_is_phone_hidden,item_is_message_forbidden,item_infm_params_text,item_id,item_description_raw,item_category_id
0,скупка телевизоров,652430,0,,114,Скупка б/у техники,91.0,4.989011,1.000000000000000,2303374,39.712818145751953,652430,54.629230499267578,True,False,Вид услуги Место оказания услуг Первомайский п...,e8b685dffe1a408e,Скупаю практически любую современную новую и б...,114
1,автоподбор,640860,0,Рейтинг пользователя 4 звезды и выше,114,Автоподбор Разовый осмотр автомобиля,462.0,4.982684,3500.000000000000000,2303374,44.051009999999998,640860,56.273389999999999,False,False,Вид услуги Место оказания услуг Нижний Новгоро...,92e1b0446f827b59,🚗 Автоподбор и выездная диагностика автомобиля...,114
2,баня на дровах,653240,0,"Онлайн-запись Тип услуги СПА-услуги, массаж Ви...",114,"Баня на дровах ""Прованс"" на Цветочной",NaN,NaN,1600.000000000000000,86469,30.128784180000000,653240,59.783687590000000,False,False,"Вид услуги Красота, здоровье Место оказания ус...",624846856ce81d69,В ритме современной жизни так сложно найти мо...,114
3,изготовление госномера на авто,634670,0,"Вид услуги Оборудование, производство",114,"Изготовление дубликатов авто номеров, гос номеров",14.0,4.714286,1700.000000000000000,2303428,40.537841000000000,633570,45.424875000000000,False,False,"Вид услуги Оборудование, производство Тип услу...",45b8628b9c6e7b85,Изготовим дубликат номера по утере или износу ...,114
4,укладка плитки,658430,0,Тип услуги Ремонт квартир и домов под ключ Вид...,114,Ремонт и отделка квартир под ключ,1.0,5.000000,1000.000000000000000,44725,69.496444699999998,658430,56.105983729999998,False,False,Вид услуги Ремонт и отделка Тип услуги Ремонт ...,c95a4a7daf2a967f,отделочные работы любой сложности.,114

,item_title_raw,item_rating_reviews_count,item_rating,item_price,item_microcat_id,item_longitude,item_location_id,item_latitude,item_is_phone_hidden,item_is_message_forbidden,item_infm_params_text,item_id,item_description_raw,item_category_id
0,Ремонт/выкуп компьют. и ноутбуков с выездом на...,57.0,5.0,500.000000000000000,2097573,42.047193961004901,631060,44.228180450924000,False,False,Вид услуги Компьютерная помощь Место оказания ...,111eb8b979577d79,"Выезд на дом в любое время, вплоть до 23:00\n\...",114
1,Обучение ребенка чтению,7.0,5.0,900.000000000000000,86453,49.627391820000000,631870,58.627609249999999,False,False,"Вид услуги Обучение, курсы Место оказания услу...",75fc8e10f5a66fc4,"Дорогие родители и маленькие книголюбы! \n\nЯ,...",114
2,Афрокудри 5+,14.0,5.0,1000.000000000000000,86467,40.936892000000000,628500,56.990307000000001,True,False,"Вид услуги Красота, здоровье Место оказания ус...",3f6ae81704565b9c,ВНИМАНИЕ Укладка !!!! 🥳\n\nАФРОкудри отличный ...,114
3,Монтаж малых архитектурных форм,2.0,5.0,5000.000000000000000,2058739,37.576183000000000,637640,55.662734999999998,False,False,Вид услуги Строительство Место оказания услуг ...,0618dec37a59a21a,Оказываем все виды услуг по сборке и монтажу и...,114
4,Репетитор по истории 10 класс ЕГЭ,19.0,5.0,1500.000000000000000,86456,44.750473999999997,624850,48.786008000000002,False,False,"Вид услуги Обучение, курсы Место оказания услу...",13da2c81574677ed,🚀 Сдай ЕГЭ по истории на 80+ за 6 месяцев!\n\n...,114

,query_id,search_query,search_location_id,search_is_delivery_search,search_infm_params_text,search_category
0,70DfDUpwjxB4lzFd,перевозки владикавказ тбилиси,649820,0,,114
1,JTrdTaZJvSiLPkXj,обзвон по базе,107620,0,Вид услуги Деловые услуги,114
2,LZCZNoVG4AFUkVRJ,липоредукция подбородка,637640,0,"Вид услуги Красота, здоровье",114
3,660ac9QVtXkRxZC3,подъемник 4 х стоечный,662810,0,,114
4,YgHcM9MVbxKnxD1e,монтаж видеодомофонов,642790,0,,114

In [4]:
#Здесь базово выведено для каждой таблицы пропуски, уникальные значения и типы данных чтобы понять, какую работу с данными надо проделать,что изменить и что не использовать.
import pandas as pd

def get_data_report(df, dataset_name):
    print(f"--- Сводка по датасету: {dataset_name} ---")
    print(f"Размер: {df.shape[0]} строк, {df.shape[1]} колонок\n")
    
    report = pd.DataFrame({
        'Тип данных': df.dtypes,
        'Пропусков (шт)': df.isna().sum(),
        'Пропусков (%)': (df.isna().sum() / len(df) * 100).round(2),
        'Уникальных значений': df.nunique()
    })
    
    display(report)
    

get_data_report(benchmark_queries, "Queries (Запросы)")
get_data_report(benchmark_items, "Items (Объявления)")
get_data_report(train, "Train (Обучающая выборка)")

--- Сводка по датасету: Queries (Запросы) ---
Размер: 2452 строк, 6 колонок

,Тип данных,Пропусков (шт),Пропусков (%),Уникальных значений
query_id,object,0,0.0,2452
search_query,object,0,0.0,2452
search_location_id,int64,0,0.0,273
search_is_delivery_search,int32,0,0.0,1
search_infm_params_text,object,0,0.0,132
search_category,int64,0,0.0,2

--- Сводка по датасету: Items (Объявления) ---
Размер: 189212 строк, 14 колонок

,Тип данных,Пропусков (шт),Пропусков (%),Уникальных значений
item_title_raw,object,0,0.00,119952
item_rating_reviews_count,float64,11615,6.14,1170
item_rating,float64,17631,9.32,6007
item_price,object,0,0.00,2949
item_microcat_id,int64,0,0.00,752
item_longitude,object,1,0.00,120004
item_location_id,int64,0,0.00,2877
item_latitude,object,1,0.00,119778
item_is_phone_hidden,bool,0,0.00,2
item_is_message_forbidden,bool,0,0.00,2
item_infm_params_text,object,0,0.00,187397
item_id,object,0,0.00,189212
item_description_raw,object,35,0.02,168134
item_category_id,int64,0,0.00,47

--- Сводка по датасету: Train (Обучающая выборка) ---
Размер: 497673 строк, 19 колонок

,Тип данных,Пропусков (шт),Пропусков (%),Уникальных значений
search_query,object,0,0.00,74529
search_location_id,int64,0,0.00,2782
search_is_delivery_search,int32,0,0.00,2
search_infm_params_text,object,0,0.00,3724
search_category,int64,0,0.00,4
item_title_raw,object,0,0.00,210029
item_rating_reviews_count,float64,19211,3.86,1372
item_rating,float64,28232,5.67,8832
item_price,object,0,0.00,2992
item_microcat_id,int64,0,0.00,212
item_longitude,object,4,0.00,228567
item_location_id,int64,0,0.00,2637
item_latitude,object,4,0.00,227858
item_is_phone_hidden,bool,0,0.00,2
item_is_message_forbidden,bool,0,0.00,2
item_infm_params_text,object,0,0.00,343205
item_id,object,0,0.00,344825
item_description_raw,object,0,0.00,327348
item_category_id,int64,0,0.00,8

In [5]:
#работа с данными.
#склеил строки с текстовым описанием,чтобы можно было подавать текст в трансформер в удобном виде
# также были заменены 35 пропусков в item_description на пустые, так как при склейке с NaN получается Nan
benchmark_items['item_description_raw'] = benchmark_items['item_description_raw'].fillna('')
train['item_description_raw'] = train['item_description_raw'].fillna('')


benchmark_items['item_full_text'] = (
    benchmark_items['item_title_raw'] + " " + 
    benchmark_items['item_description_raw'] + " " + 
    benchmark_items['item_infm_params_text']
).str.lower()

 
benchmark_queries['query_full_text'] = (
    benchmark_queries['search_query'] + " " + 
    benchmark_queries['search_infm_params_text']
).str.lower()



for df in [benchmark_items, train]:
    df['item_rating_reviews_count'] = df['item_rating_reviews_count'].fillna(0)
    df['item_rating'] = df['item_rating'].fillna(-1)
    
  
    df['item_latitude'] = pd.to_numeric(df['item_latitude'], errors='coerce')
    df['item_longitude'] = pd.to_numeric(df['item_longitude'], errors='coerce')
    
  
    df['item_latitude'] = df.groupby('item_location_id')['item_latitude'].transform(lambda x: x.fillna(x.mean()))
    df['item_longitude'] = df.groupby('item_location_id')['item_longitude'].transform(lambda x: x.fillna(x.mean()))
    
   
    df['item_latitude'] = df['item_latitude'].fillna(0)
    df['item_longitude'] = df['item_longitude'].fillna(0)

In [6]:
# здесь проверил совпадают  ли местополоожение и категория в train(чтобы понимать зависимость)
print((train['search_location_id'] == train['item_location_id']).mean())

print((train['search_category'] == train['item_category_id']).mean())

0.8310195650557696
0.9998935043693349

In [7]:
import pandas as pd
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

#Загружаем базу.Тексты макс 64 токена,иначе вылетает.
model = SentenceTransformer('cointegrated/rubert-tiny2', device=device)
model.max_seq_length = 64

# Берем весь трейн с перемешиванием
train_subset = train.sample(n=497673, random_state=42).reset_index(drop=True)

# Склеиваем заголовок и описание для более плотного контекста
queries = train_subset['search_query'].fillna('')
item_titles = train_subset['item_title_raw'].fillna('')
item_descriptions = train_subset['item_description_raw'].fillna('')
item_full_texts = item_titles + " " + item_descriptions

# Формируем пары (запрос -> кликнутое объявление)
train_examples = []
for q, text in zip(queries, item_full_texts):
    if len(q) > 0 and len(text) > 0: 
        train_examples.append(InputExample(texts=[str(q), str(text)]))

print(f"Собрано {len(train_examples)} пар для обучения. Запускаем...")

# Батч 64 — адекватный лимит под доступную VRAM
train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=64)

# Используем in-batch negatives
train_loss = losses.MultipleNegativesRankingLoss(model=model)

#обучение на одной эпохе
model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=1,         
    warmup_steps=100, 
    show_progress_bar=True,
    output_path='./rubert-tiny2-avito-tuned'
)
print("Обучение завершено! Модель сохранена.")

/tmp/ipykernel_1713/1896702336.py:2: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers import SentenceTransformer, InputExample, losses
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/55 [00:00<?, ?it/s]

BertModel LOAD REPORT from: cointegrated/rubert-tiny2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.embeddings.position_ids               | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Собрано 497673 пар для обучения. Запускаем градиентный спуск...

Currently using DataParallel (DP) for multi-gpu training, while DistributedDataParallel (DDP) is recommended for faster training. See https://sbert.net/docs/sentence_transformer/training/distributed.html for more information.

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Обучение завершено! Модель сохранена.

In [8]:
from sentence_transformers import SentenceTransformer
import torch
import pandas as pd
from tqdm.notebook import tqdm

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Поднимаем нашу дообученную модель с диска
tuned_model = SentenceTransformer('./rubert-tiny2-avito-tuned', device=device)
tuned_model.max_seq_length = 64

print("Генерация новых векторов...")
#применение к items модели готовой
items_embeddings_tuned = tuned_model.encode(
    benchmark_items['item_full_text'].tolist(),
    batch_size=256, show_progress_bar=True, convert_to_tensor=True, normalize_embeddings=True
)
#применеие к queries модели готовой 
queries_embeddings_tuned = tuned_model.encode(
    benchmark_queries['query_full_text'].tolist(),
    batch_size=256, show_progress_bar=True, convert_to_tensor=True, normalize_embeddings=True
)

#перекидываем фичи локаций на GPU, чтобы быстро работало
item_locs = torch.tensor(benchmark_items['item_location_id'].values, device=device)
item_ids = benchmark_items['item_id'].values
predictions = []

print("Поиск кандидатов...")
for idx, query_row in tqdm(benchmark_queries.iterrows(), total=len(benchmark_queries)):
    q_vec = queries_embeddings_tuned[idx]
    q_loc = query_row['search_location_id']

    #косинусное расстояние считаем
    sim_scores = torch.mv(items_embeddings_tuned, q_vec)
    
    # объявления из одного города бустим
    sim_scores += (item_locs == q_loc).float() * 0.2

    #вытаскиваем топ 50 подходящих
    top_indices = torch.topk(sim_scores, k=50).indices.cpu().numpy()
    predictions.append(' '.join(item_ids[top_indices]))

answer = pd.DataFrame({
    'query_id': benchmark_queries['query_id'],
    'answer': predictions
})
answer.to_csv('answer_tuned.csv', index=False)
print("Файл answer_tuned.csv успешно создан!")

Loading weights:   0%|          | 0/55 [00:00<?, ?it/s]

Генерация новых векторов...

Batches:   0%|          | 0/740 [00:00<?, ?it/s]

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

Поиск кандидатов...

  0%|          | 0/2452 [00:00<?, ?it/s]

Файл answer_tuned.csv успешно создан!